import styles from '@/styles/Home.module.css';
import { CheckoutWithCard, PaperSDKProvider } from '@paperxyz/react-client-sdk';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<PaperSDKProvider appName="My Web3 App" chainName="Polygon">
					<CheckoutWithCard
						sdkClientSecret="MY_SDK_CLIENT_SECRET"
						onPaymentSuccess={(result: any) => {
							console.log('Payment successful.');
						}}
						onError={(error: any) => {
							console.error('Payment error:', error);
						}}
						options={{
							colorBackground: '#121212',
							colorPrimary: '#19A8D6',
							colorText: '#f0f0f0',
							borderRadius: 24,
						}}
					/>
				</PaperSDKProvider>
			</main>
		</>
	);
}
